### ISSUE TITLE
Conda package of VISAN for Windows is not available

### ISSUE THREAD

**Issue by OPTICSFOOL** [stcorp/visan#5]
I used the following instructions：

conda install --channel https://conda.anaconda.org/stcorp visan

But Anaconda told me：

PackagesNotFoundError: The following packages are not available from current channels:
  - visan

**Comment by svniemeijer** [comment]
We are encountering an issue with anaconda uploads that silently fail. This seems to be some issue with the anaconda toolset, which is out of our control. We are trying to find a workaround, but this is rather difficult.

We just manually uploaded the visan packages for windows again.
