### ISSUE TITLE
raise CLibraryError() using harp.import_product

### ISSUE THREAD

**Issue by sarabarozzi2811** [stcorp/visan#6]
I am using Windows. When I try to use harp.import_product from visan it does not work, while when I use warp inside python it works. 
can you please fix it?

![image](https://user-images.githubusercontent.com/29089503/78363735-927a2000-75bc-11ea-806d-00c92a6cc2ed.png)

**Comment by svniemeijer** [comment]
It seems the new conda packages for HARP for windows also didn't get uploaded (some as #5).
We just did this manually. Can you clarify whether updating your conda environment works for you?

**Comment by sarabarozzi2811** [comment]
I created a new environment and installed visan again and now it works! thank you!!
