### ISSUE TITLE
wplot picks inconvenient default variable for S5P AI products

### ISSUE THREAD

**Issue by giovanniscaggiante** [stcorp/visan#7]
When i try to plot "S5P_OFFL_L2__AER_AI_20190517T092621_20190517T110751_08243_01_010301_20190523T085237.nc"
it shows the "surface meridional wind velocity" but it should be the "absorbing aerosol index" (i'm following a tutorial)
![test](https://user-images.githubusercontent.com/65983082/82954631-6d4ad200-9fad-11ea-9dc6-adef3cdf044c.png)
how can it be possible?

**Comment by svniemeijer** [comment]
You can use `wplot(product, value="absorbing_aerosol_index")`

**Comment by giovanniscaggiante** [comment]
thanks for the quick help.
